print(r'''1. How old are you? (Promise we won't tell)''')
print('''Under 30''')
print('''a. 30s''')
print('''b. 40s''')
print('''c. 50s''')
print('''d. 60s''')
a = input('Please Choose one: ')
print(r'''2. What is your status?''')
print("a. Single")
print("b. Married")
print("c. Divorced")
b = input('Please Choose one: ')
print(r'''3. Bringing home the bacon - what's your annual household income?''')
print("a. Under $75,000")
print("b. $75,000 to $125,000")
print("c. $125,000 to $200,000")
print("d. $200,000 to $400,000")
print("e. Over $400,000")
c = input('Please Choose one: ')
print(r'''4. How much do you have in total savings? i.e. retirement, investments & cash accounts.''')
print("a. Under $100,000")
print("b. $100,000 to $400,000")
print("c. $400,000 to $800,000")
print("e. $800,000 to $1,500,000")
print("f. $1,500,000 to $4,000,000")
print("g. Over $4,000,000")
d = input('h. Please Choose one: ')
print(r'''5. Do you own a business?''')
print(r"Yes\No")
e = input('Please Choose one: ')
print(r'''6. Are you currently working with a financial advisor?''')
print(r"No\Yes")
f = input('Please Choose one: ')
print(r'''7. What type of service are you looking for?''')
print('a. Financial Planning')
print('b. Investment Management')
print('c. Both')
print('d. Unsure')
print('e. Something Else')
g = input('Please Choose one: ')
    print(r'''8. What type of relationship are you looking for?''')
print('a. One Time Plan')
print('b. Ongoing Advice')
print('c. Unsure')
h = input('Please Choose one: ')
print(r'''9. How important is having your financial advisor within driving distance?''')
print('a. Not important')
print('b. Nice to have')
print('c. Very important')
i = input('Please Choose one: ')
print(r'''10. Which of the following best describes your goals? (Max 5)''')
print('a. Prepare for retirement')
print("b. Save for kid's college")
print('c. Access to alternative investments')
print('d. Diversify concentrated wealth')
print('e. Manage my inheritance')
print('f. Optimize my taxes')
print('g. Pay down debt')
print('h. Start my own business')
print('i. Manage new wealth')
print('j. Socially responsible investingm')
print('k. Philanthropy')
print('l. Improve budgeting')
j, k, l, m, n = input("Please Choose any five(separated by ',' ): ")
print(r'''11. Zip Code''')
o = input('Please Enter Zip Code: ')




